import { _decorator, Component, Node,game } from 'cc';
import { TileType } from './GridManager';
const { ccclass, property } = _decorator;

export interface Level {
    stdMoves:number;
    size:number;
    grid:number[][];
}

const Levels:Level[] = [
    {
        stdMoves:1,
        size:3,
        grid:[
            [0,0,0],
            [0,0,0],
            [0,0,0]
        ]
    },
    {
        stdMoves:1,
        size:3,
        grid:[
            [1,1,1],
            [1,0,0],
            [1,0,0]
        ]
    },
    {
        stdMoves:2,
        size:3,
        grid:[
            [0,0,0],
            [0,1,1],
            [0,1,1]
        ]
    },
    {
        stdMoves:3,
        size:3,
        grid:[
            [1,1,0],
            [1,0,1],
            [0,1,1]
        ]
    },
    {
        stdMoves:1,
        size:3,
        grid:[
            [1,1,1],
            [0,0,0],
            [0,0,0]
        ]
    },
    {
        stdMoves:2,
        size:3,
        grid:[
            [1,1,1],
            [0,1,1],
            [0,1,1]
        ]
    },
    {
        stdMoves:3,
        size:3,
        grid:[
            [1,1,1],
            [1,0,1],
            [1,0,1]
        ]
    },
    {
        stdMoves:2,
        size:3,
        grid:[
            [0,1,0],
            [0,1,0],
            [1,0,0]
        ]
    },
    {
        stdMoves:3,
        size:3,
        grid:[
            [0,1,0],
            [0,0,1],
            [1,0,0]
        ]
    },
    {
        stdMoves:2,
        size:3,
        grid:[
            [0,1,1],
            [0,1,1],
            [1,0,0]
        ]
    },
    {
        stdMoves:3,
        size:3,
        grid:[
            [0,1,1],
            [1,0,0],
            [1,1,1]
        ]
    },
    {
        stdMoves:3,
        size:3,
        grid:[
            [0,0,1],
            [0,0,1],
            [0,1,0]
        ]
    },
    {
        stdMoves:1,
        size:4,
        grid:[
            [1,1,1,1],
            [1,0,0,0],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        stdMoves:2,
        size:4,
        grid:[
            [1,1,1,1],
            [1,0,0,0],
            [1,0,1,1],
            [1,0,1,1]
        ]
    },
    {
        stdMoves:2,
        size:4,
        grid:[
            [0,0,1,1],
            [0,1,0,0],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        stdMoves:3,
        size:4,
        grid:[
            [0,0,1,1],
            [0,1,0,0],
            [1,0,1,1],
            [1,0,1,1]
        ]
    },
    {
        stdMoves:3,
        size:4,
        grid:[
            [0,0,0,0],
            [0,1,1,1],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        stdMoves:4,
        size:4,
        grid:[
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0]
        ]
    },
    {
        stdMoves:2,
        size:4,
        grid:[
            [0,0,0,0],
            [0,0,0,0],
            [0,0,1,1],
            [1,1,1,1]
        ]
    },
    {
        stdMoves:2,
        size:4,
        grid:[
            [1,1,0,0],
            [1,1,0,0],
            [1,0,1,1],
            [1,0,0,0]
        ]
    },
    {
        stdMoves:3,
        size:4,
        grid:[
            [1,1,0,0],
            [1,0,1,1],
            [0,1,0,0],
            [0,1,0,0]
        ]
    },
    {
        stdMoves:4,
        size:4,
        grid:[
            [1,0,1,1],
            [1,1,0,0],
            [0,1,0,0],
            [0,1,0,0]
        ]
    },
    {
        stdMoves:2,
        size:5,
        grid:[
            [1,1,1,1,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [1,1,1,1,1]
        ]
    },
    {
        stdMoves:3,
        size:5,
        grid:[
            [0,0,0,1,1],
            [1,0,0,0,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [1,1,1,1,1]
        ]
    },
    {
        stdMoves:3,
        size:5,
        grid:[
            [1,1,0,0,0],
            [1,1,0,-2,0],
            [1,1,0,0,0],
            [1,1,1,1,1],
            [1,1,1,1,1]
        ]
    },
]

export function getLevel(index:number) {
    if(index>=Levels.length){
        game.end();
    }
    return Levels[index];
}