import { _decorator, Component, Node,game } from 'cc';
import { TileType } from './GridManager';
const { ccclass, property } = _decorator;

export interface Level {
    level:number;
    stdMoves:number;
    size:number;
    grid:number[][];
}

const Levels:Level[] = [
    {
        level:1,
        stdMoves:1,
        size:3,
        grid:[
            [0,0,0],
            [0,0,0],
            [0,0,0]
        ]
    },
    {
        level:2,
        stdMoves:1,
        size:3,
        grid:[
            [1,1,1],
            [1,0,0],
            [1,0,0]
        ]
    },
    {
        level:3,
        stdMoves:2,
        size:3,
        grid:[
            [0,0,0],
            [0,1,1],
            [0,1,1]
        ]
    },
    {
        level:4,
        stdMoves:3,
        size:3,
        grid:[
            [1,1,0],
            [1,0,1],
            [0,1,1]
        ]
    },
    {
        level:5,
        stdMoves:1,
        size:3,
        grid:[
            [1,1,1],
            [0,0,0],
            [0,0,0]
        ]
    },
    {
        level:6,
        stdMoves:2,
        size:3,
        grid:[
            [1,1,1],
            [0,1,1],
            [0,1,1]
        ]
    },
    {
        level:7,
        stdMoves:3,
        size:3,
        grid:[
            [1,1,1],
            [1,0,1],
            [1,0,1]
        ]
    },
    {
        level:8,
        stdMoves:2,
        size:3,
        grid:[
            [0,1,0],
            [0,1,0],
            [1,0,0]
        ]
    },
    {
        level:9,
        stdMoves:1,
        size:4,
        grid:[
            [1,1,1,1],
            [1,0,0,0],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        level:10,
        stdMoves:2,
        size:4,
        grid:[
            [1,1,1,1],
            [1,0,0,0],
            [1,0,1,1],
            [1,0,1,1]
        ]
    },
    {
        level:11,
        stdMoves:2,
        size:4,
        grid:[
            [0,0,1,1],
            [0,1,0,0],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        level:12,
        stdMoves:3,
        size:4,
        grid:[
            [0,0,1,1],
            [0,1,0,0],
            [1,0,1,1],
            [1,0,1,1]
        ]
    },
    {
        level:13,
        stdMoves:3,
        size:4,
        grid:[
            [0,0,0,0],
            [0,1,1,1],
            [1,0,0,0],
            [1,0,0,0]
        ]
    },
    {
        level:14,
        stdMoves:4,
        size:4,
        grid:[
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0]
        ]
    },
    {
        level:15,
        stdMoves:2,
        size:4,
        grid:[
            [0,0,0,0],
            [0,0,0,0],
            [0,0,1,1],
            [1,1,1,1]
        ]
    },
    {
        level:16,
        stdMoves:2,
        size:4,
        grid:[
            [1,1,0,0],
            [1,1,0,0],
            [1,0,1,1],
            [1,0,0,0]
        ]
    },
    {
        level:17,
        stdMoves:3,
        size:4,
        grid:[
            [1,1,0,0],
            [1,0,1,1],
            [0,1,0,0],
            [0,1,0,0]
        ]
    },
    {
        level:18,
        stdMoves:4,
        size:4,
        grid:[
            [1,0,1,1],
            [1,1,0,0],
            [0,1,0,0],
            [0,1,0,0]
        ]
    },
    {
        level:19,
        stdMoves:2,
        size:5,
        grid:[
            [1,1,1,1,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [1,1,1,1,1]
        ]
    },
    {
        level:20,
        stdMoves:3,
        size:5,
        grid:[
            [0,0,0,1,1],
            [1,0,0,0,1],
            [0,1,1,0,1],
            [0,1,1,0,1],
            [1,1,1,1,1]
        ]
    },
    {
        level:21,
        stdMoves:3,
        size:5,
        grid:[
            [1,1,0,0,0],
            [1,1,0,-2,0],
            [1,1,0,0,0],
            [1,1,1,1,1],
            [1,1,1,1,1]
        ]
    },
]

export function getLevel(index:number) {
    if(index>=Levels.length){
        game.end();
    }
    return Levels[index];
}